name: transformer-adapter
channels:
  - defaults
dependencies:
  - python=3.7
  - pip
  - pip:
    - pytorch
    - numpy
    - pandas
    - sklearn
    - adapter-transformers
    - transformers
    - datasets
    - TensorFlow