ROBERTA_CLASSIFIER_SMALL = {
    "LEARNING_RATE": 2e-5,
    "DROPOUT": 0.1,
    "ENCODER": "CLS",
    "NUM_FEEDFORWARD_LAYERS": 1,
    "FEEDFORWARD_WIDTH_MULTIPLIER": 1,
    "EMBEDDING": "ROBERTA",
    "NUM_EPOCHS": 10,
    "PATIENCE": 3,
    "LR_SCHEDULE": 0,
    "GRAD_ACC_BATCH_SIZE": 16,
    "BATCH_SIZE": 16
}